version: 2
defaults: &defaults
  docker:
    - image: circleci/node:8.12
jobs:
  install:
    <<: *defaults
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-cross-fetch-{{ .Branch }}-{{ checksum "package-lock.lock" }}
            - v1-cross-fetch-{{ .Branch }}-
            - v1-cross-fetch-
      - run: npm install
      - save_cache:
          key: v1-cross-fetch-{{ .Branch }}-{{ checksum "package-lock.lock" }}
          paths:
            - node_modules/
  cross-browser:
    <<: *defaults
    steps:
      - checkout
      - run: npm install
      - run: make sauce
  test:
    <<: *defaults
    steps:
      - checkout
      - run: sudo apt-get update
      - run:
          # This is needed for puppeteer to work inside the container
          sudo apt-get install -yq --no-install-recommends gconf-service libasound2 libatk1.0-0 libatk-bridge2.0-0 libc6 libcairo2 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libpangocairo-1.0-0 libstdc++6 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation libappindicator1 libnss3 lsb-release xdg-utils wget
      - run: make test
      - run: make cov
  security:
    <<: *defaults
    steps:
      - checkout
      - run: make snyk
  publish:
    <<: *defaults
    steps:
      - checkout
      - run: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" >> ~/.npmrc
      - run: npm publish
workflows:
  version: 2
  cross-fetch:
    jobs:
      - install
      - cross-browser:
          requires:
            - install
      - security
      - test:
          requires:
            - install
      - publish:
          type: approval
          requires:
            - cross-browser
            - security
            - test
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /v\d+\.\d+\.\d+(-\S+)?/

