# Based on https://docs.github.com/en/actions/guides/publishing-nodejs-packages#publishing-packages-to-npm-and-github-packages
name: Release

on:
  release:
    types: [created]

jobs:
  # npm:
  #   name: NPM Registry
  #   runs-on: ubuntu-latest
  #   steps:
  #   - uses: actions/checkout@v2
  #   # Setup .npmrc file to publish to npm
  #   - uses: actions/setup-node@v1
  #     with:
  #       node-version: '10.x'
  #       registry-url: 'https://registry.npmjs.org'
  #   - run: npm publish
  #     env:
  #       NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  github:
    name: Github Registry
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    # Setup .npmrc file to publish to GitHub Packages
    - uses: actions/setup-node@v1
      with:
        registry-url: 'https://npm.pkg.github.com'
    - run: npm publish
      env:
        NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
