# The security job must be in a different workflow since the SNYK_TOKEN variable
# cannot be passed to pull requests opened from forks. It would fail every time.
name: Security

on:
  push:
    branches: [ main ]

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-node@v2
    - run: npm install
    - run: make secure
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
